all:
  vars:
    ansible_connection: ssh
    http_port: 80
    ansible_python_interpreter: /usr/bin/python3

  children:
    web:
      hosts:
        web-server:
          ansible_host: 171.244.27.138
          ansible_port: 25022
          ansible_user: root
          ansible_ssh_private_key_file: /working-dir/SSHKey/kube-key
          ansible_python_interpreter: /usr/bin/python3

    backend:
      hosts:
        web-server:
