---
- name: Install and configure Nginx web server
  hosts: all
  become: true

  vars:
    src_path_file: ../files/index.html
    src_path_template: ../templates/nginx.conf.j2

  tasks:
    - name: Install Nginx service
      ansible.builtin.apt:
        name: nginx
        state: present
      when: ansible_os_family == 'Debian'

    - name: Create a directory for web content
      ansible.builtin.file:
        path: "{{ web_root }}"
        state: directory
        mode: '0755'
      tags: setup

    - name: Copy HTML file to web root
      ansible.builtin.copy:
        src: "{{ src_path_file }}"
        dest: "{{ web_root }}/index.html"
        mode: '0644'
      notify: Restart Nginx
      tags: content

    - name: Configure Nginx using template
      ansible.builtin.template:
        src: "{{ src_path_template }}"
        dest: /etc/nginx/conf.d/ansible-app.conf
        mode: '0644'
      notify: Restart Nginx
      tags: config

  handlers:
    - name: Restart Nginx
      ansible.builtin.service:
        name: nginx
        state: restarted
