---
- name: Use handlers to optimize Playbook
  hosts: all
  become: true

  vars:
    src_path_index: ../templates/index.html.j2
    src_path_nginx: ../templates/nginx.conf.j2

  tasks:
    - name: Make sure the web root directory exists
      ansible.builtin.file:
        path: "{{ web_root }}"
        state: directory
        mode: '0755'

    - name: Update index.html with new content
      ansible.builtin.template:
        src: "{{ src_path_index }}"
        dest: "{{ web_root }}/index.html"
        mode: '0644'
      notify: Restart Nginx

    - name: Update nginx.conf via template
      ansible.builtin.template:
        src: "{{ src_path_nginx }}"
        dest: /etc/nginx/conf.d/ansible-app.conf
        mode: '0644'
      notify: Restart Nginx

    - name: Flush handlers
      ansible.builtin.meta: flush_handlers

    - name: Website access check
      ansible.builtin.uri:
        url: http://localhost/
        return_content: true
        status_code: 200
      register: web_result

    - name: Print web result
      ansible.builtin.debug:
        var: web_result.content

  handlers:
    - name: Restart Nginx
      ansible.builtin.service:
        name: nginx
        state: restarted
