---
- name: Demo authentication with Ansible Vault
  hosts: all
  become: false

  vars_files:
    - ../vault/secrets.yml

  tasks:
    - name: Print the database password
      ansible.builtin.debug:
        msg: "The database password is {{ db_password }}"
