---
- name: Ping remote host
  hosts: all
  gather_facts: no
  tasks:
    - name: Ping the remote host
      ansible.builtin.ping:

    - name: Create a directory web
      ansible.builtin.file:
        path: "{{ web_root }}"
        state: directory
        mode: '0755'
